import Link from "next/link";
import { AppShell } from "@/components/AppShell";
import { rankingMetrics, rankingPeriods, type RankingViewProps, type RankingRow } from "../Model";

const periodLabels = { daily: "Hoje", weekly: "Semana", monthly: "Mês", global: "Geral" };
const metricLabels = { xp: "XP", words: "Palavras dominadas", streak: "Sequência" };

function RankingTable({ rows, userId, suffix }: { rows: RankingRow[]; userId: string; suffix: string }) {
  return rows.length ? <ol className="mt-5 space-y-2">{rows.map((row) => <li key={row.userId} className={`flex items-center justify-between gap-4 rounded-xl border p-4 ${row.userId === userId ? "border-emerald-500 bg-emerald-50 text-emerald-950" : "border-[var(--border)]"}`}><div className="flex min-w-0 items-center gap-3"><span className="w-8 shrink-0 font-extrabold text-primary">{row.place}º</span><span className="truncate font-bold">{row.name}{row.userId === userId && " (você)"}</span></div><strong className="shrink-0">{row.score.toLocaleString("pt-BR")} {suffix}</strong></li>)}</ol> : <p className="mt-5 text-muted">Ainda não há participantes com pontuação neste período.</p>;
}

export function RankingView({ period, metric, rows, league, userId, error }: RankingViewProps) {
  return <AppShell active="/ranking"><div className="mx-auto max-w-4xl"><p className="eyebrow">Comunidade</p><h1 className="mt-2 text-3xl font-extrabold sm:text-4xl">Ranking e ligas</h1><p className="mt-2 text-muted">Apenas estudantes que ativaram “Aparecer no ranking público” são exibidos.</p>{error ? <section className="surface mt-8 p-7" role="alert">Não foi possível carregar o ranking agora. Tente novamente mais tarde.</section> : <><section className="surface mt-8 p-6"><h2 className="text-xl font-extrabold">Ranking público</h2><div className="mt-5 flex flex-wrap gap-2" aria-label="Período do ranking">{rankingPeriods.map((item) => <Link key={item} href={`/ranking?period=${item}&metric=${metric}`} aria-current={period === item ? "page" : undefined} className={period === item ? "button-primary text-sm" : "button-secondary text-sm"}>{periodLabels[item]}</Link>)}</div><div className="mt-3 flex flex-wrap gap-2" aria-label="Métrica do ranking">{rankingMetrics.map((item) => <Link key={item} href={`/ranking?period=${period}&metric=${item}`} aria-current={metric === item ? "page" : undefined} className={metric === item ? "button-primary text-sm" : "button-secondary text-sm"}>{metricLabels[item]}</Link>)}</div><RankingTable rows={rows} userId={userId} suffix={metric === "xp" ? "XP" : metric === "words" ? "palavras" : "dias"} /></section><section className="surface mt-6 p-6"><h2 className="text-xl font-extrabold">Sua liga semanal</h2>{!league?.membership.participating ? <div><p className="mt-3 text-muted">Ative a participação pública nas configurações para entrar na liga.</p><Link href="/settings" className="button-secondary mt-5">Abrir configurações</Link></div> : <><p className="mt-3 text-muted">Liga {league.membership.leagueName} · semana de {league.membership.weekStart}</p><p className="mt-2 text-sm text-muted">Os melhores 20% sobem de liga após a semana. Apenas os últimos 10% ativos podem descer; semanas sem atividade não rebaixam.</p><RankingTable rows={league.rows} userId={userId} suffix="XP" /></>}</section></>}</div></AppShell>;
}
