import Link from "next/link";
import type { LandingViewProps } from "../Model";
import { PwaControls } from "@/components/PwaControls";

export function LandingView({ benefits, primaryHref, secondaryHref }: LandingViewProps) {
  return <main className="min-h-screen overflow-hidden"><div className="mx-auto max-w-6xl px-5 sm:px-8">
    <header className="flex items-center justify-between gap-3 py-7"><Link href="/" className="flex items-center gap-3 text-xl font-extrabold tracking-tight" aria-label="English Journey, início"><span className="flex h-10 w-10 items-center justify-center rounded-xl bg-primary text-white">E<span className="text-amber-300">J</span></span>English Journey</Link><div className="flex items-center gap-3"><PwaControls /><Link href={secondaryHref} className="text-sm font-bold text-primary hover:underline">Entrar</Link></div></header>
    <section className="grid min-h-[580px] items-center gap-10 py-12 md:grid-cols-2 md:py-20"><div><p className="eyebrow mb-5">Uma jornada, muitas possibilidades</p><h1 className="max-w-xl text-5xl leading-[1.08] font-extrabold tracking-tight sm:text-6xl">O inglês abre portas. <span className="text-primary">Comece a sua jornada.</span></h1><p className="mt-7 max-w-lg text-lg leading-8 text-muted">Aprenda com passos pequenos, pratique todos os dias e veja até onde você pode chegar.</p><div className="mt-9 flex flex-col gap-3 sm:flex-row"><Link className="button-primary" href={primaryHref}>Começar gratuitamente <span aria-hidden>→</span></Link><Link className="button-secondary" href="#como-funciona">Como funciona</Link></div><p className="mt-5 text-sm text-muted">Crie uma conta e defina sua primeira meta em minutos.</p></div>
      <div className="relative mx-auto w-full max-w-[490px]" aria-hidden="true"><div className="absolute -inset-8 rounded-full bg-emerald-100 blur-3xl" /><div className="surface relative rotate-2 p-6 sm:p-8"><div className="mb-8 flex items-center justify-between"><span className="rounded-full bg-emerald-100 px-4 py-2 text-sm font-bold text-emerald-800">Sua jornada hoje</span><span className="text-2xl">✦</span></div><p className="text-sm font-bold text-muted">PRÓXIMO PASSO</p><h2 className="mt-2 text-3xl font-extrabold">Seu primeiro dia de inglês</h2><p className="mt-3 text-muted">Comece com uma meta simples e construa o hábito.</p><div className="mt-8 rounded-2xl bg-[#f1f7e8] p-5"><div className="flex items-center justify-between"><span className="font-bold">Meta diária</span><span className="font-bold text-primary">20 min</span></div><div className="mt-4 h-3 rounded-full bg-white"><div className="h-3 w-1/3 rounded-full bg-primary" /></div><p className="mt-3 text-xs text-muted">Cada minuto conta.</p></div><div className="mt-4 flex gap-3"><div className="flex-1 rounded-2xl bg-[#fff4df] p-4"><span className="text-2xl">🔥</span><p className="mt-2 font-bold">Crie sua sequência</p></div><div className="flex-1 rounded-2xl bg-[#e8f4fa] p-4"><span className="text-2xl">⭐</span><p className="mt-2 font-bold">Ganhe XP</p></div></div></div></div>
    </section><section id="como-funciona" className="py-16 sm:py-24"><p className="eyebrow">Como funciona</p><h2 className="mt-3 text-3xl font-extrabold sm:text-4xl">Um caminho claro para evoluir</h2><div className="mt-8 grid gap-5 md:grid-cols-3">{benefits.map((item) => <article className="surface p-7" key={item.number}><span className="text-sm font-extrabold text-primary">{item.number}</span><h3 className="mt-5 text-xl font-bold">{item.title}</h3><p className="mt-3 leading-7 text-muted">{item.description}</p></article>)}</div></section><footer className="border-t border-[var(--border)] py-8 text-sm text-muted">© {new Date().getFullYear()} English Journey</footer>
  </div></main>;
}
