import { AppShell } from "@/components/AppShell";
import type { ProgressViewProps } from "../Model";

export function ProgressView({ data }: ProgressViewProps) {
  const accuracy = data.totalAnswers ? Math.round(data.correctAnswers / data.totalAnswers * 100) : 0;
  const lastSeven = [...data.days].slice(0, 7).reverse();
  const maxXp = Math.max(1, ...lastSeven.map((day) => day.xp_earned));
  return <AppShell active="/progress"><p className="eyebrow">Sua evolução</p><h1 className="mt-2 text-4xl font-extrabold">Progresso</h1><p className="mt-2 text-muted">Cada sessão soma à sua jornada.</p><section className="mt-8 grid gap-4 sm:grid-cols-2 lg:grid-cols-4"><Stat label="XP total" value={`${data.totalXp}`} /><Stat label="Nível" value={`${data.level}`} /><Stat label="Palavras estudadas" value={`${data.learnedWords}`} /><Stat label="Taxa de acerto (30 dias)" value={`${accuracy}%`} /></section><section className="mt-6 grid gap-6 lg:grid-cols-[1.4fr_1fr]"><article className="surface p-7"><h2 className="text-xl font-extrabold">XP nos últimos 7 dias</h2>{lastSeven.length ? <div className="mt-8 flex h-48 items-end gap-3" role="img" aria-label="Gráfico de XP diário">{lastSeven.map((day) => <div className="flex flex-1 flex-col items-center gap-2" key={day.local_date}><span className="text-xs font-bold">{day.xp_earned}</span><div className="w-full max-w-12 rounded-t-lg bg-primary" style={{ height: `${Math.max(4, day.xp_earned / maxXp * 130)}px` }} /><span className="text-xs text-muted">{day.local_date.slice(5)}</span></div>)}</div> : <p className="mt-6 text-muted">Sua atividade aparecerá aqui após os primeiros exercícios.</p>}</article><article className="surface p-7"><h2 className="text-xl font-extrabold">Seu caminho</h2><p className="mt-5 text-3xl font-extrabold text-primary">🔥 {data.streakDays} dias</p><p className="mt-2 text-sm text-muted">Sequência de metas alcançadas</p><div className="mt-6 border-t border-[var(--border)] pt-5"><p className="font-bold">{data.masteredWords} palavras dominadas</p><p className="mt-1 text-sm text-muted">Continue revisando para elevar o domínio.</p></div></article></section><section className="surface mt-6 p-7"><h2 className="text-xl font-extrabold">Conquistas</h2>{data.achievements.length ? <div className="mt-5 grid gap-3 sm:grid-cols-2 lg:grid-cols-3">{data.achievements.map((item) => <article className="rounded-xl bg-amber-50 p-4" key={item.id}><p className="font-extrabold">🏆 {item.title}</p><p className="mt-1 text-sm text-muted">{item.description}</p></article>)}</div> : <p className="mt-3 text-muted">Sua primeira conquista aparece após uma resposta correta.</p>}</section></AppShell>;
}

function Stat({ label, value }: { label: string; value: string }) { return <article className="surface p-5"><p className="text-sm font-bold text-muted">{label}</p><p className="mt-3 text-3xl font-extrabold text-primary">{value}</p></article>; }
