import Link from "next/link";
import { Bell, Trophy } from "lucide-react";
import type { AppShellProps } from "../Model";
import { getNavigation } from "../Controller";
import { PwaControls } from "@/components/PwaControls";

export function AppShellView({ children, active }: AppShellProps) {
  const links = getNavigation(active);
  return <div className="min-h-screen pb-20 md:pb-0"><header className="border-b border-[var(--border)] bg-white"><div className="mx-auto flex max-w-6xl items-center justify-between gap-3 px-3 py-4 sm:px-5"><Link href="/dashboard" className="shrink-0 text-xl font-extrabold text-primary" aria-label="English Journey"><span className="sm:hidden">EJ</span><span className="hidden sm:inline">English Journey</span></Link><nav aria-label="Navegação principal" className="hidden items-center gap-2 md:flex">{links.map((item) => <Link key={item.href} href={item.href} aria-current={item.current ? "page" : undefined} className={`rounded-xl px-3 py-2 text-sm font-bold ${item.current ? "bg-emerald-100 text-emerald-900" : "text-muted hover:bg-emerald-50"}`}>{item.label}</Link>)}</nav><div className="flex items-center gap-1 sm:gap-2"><PwaControls /><Link href="/ranking" aria-label="Ranking e ligas" className="rounded-lg px-2 py-1 text-lg text-muted hover:bg-emerald-50"><Trophy size={20} aria-hidden /></Link><Link href="/notifications" aria-label="Notificações" className="rounded-lg px-2 py-1 text-lg text-muted hover:bg-emerald-50"><Bell size={20} aria-hidden /></Link><Link href="/settings" aria-label="Configurações" className="rounded-lg px-2 py-1 text-lg text-muted hover:bg-emerald-50">⚙</Link></div></div></header><div className="mx-auto max-w-6xl px-5 py-8 sm:py-10">{children}</div><nav aria-label="Navegação móvel" className="fixed inset-x-0 bottom-0 z-20 flex justify-around border-t border-[var(--border)] bg-white px-1 py-2 md:hidden">{links.map((item) => <Link key={item.href} href={item.href} aria-current={item.current ? "page" : undefined} className={`flex min-w-14 flex-col items-center gap-1 rounded-lg px-1 py-1 text-[11px] font-bold ${item.current ? "text-primary" : "text-muted"}`}><span className="text-lg" aria-hidden>{item.symbol}</span>{item.label}</Link>)}</nav></div>;
}
