"use client";

import { AppShell } from "@/components/AppShell";
import { PushPermission } from "@/features/Push";
import { SignOutButton } from "@/components/SignOutButton";
import { saveSettings } from "../Controller";
import type { SettingsViewProps } from "../Model";

export function SettingsView({ data, saved, error }: SettingsViewProps) {
  function applyTheme(value: string) { localStorage.setItem("ej-theme", value); document.documentElement.dataset.theme = value; }
  return <AppShell active="/settings"><div className="flex items-start justify-between"><div><p className="eyebrow">Sua conta</p><h1 className="mt-2 text-4xl font-extrabold">Configurações</h1></div><SignOutButton userId={data.userId} /></div><div className="mt-8 grid gap-6 lg:grid-cols-[1.2fr_1fr]"><form action={saveSettings} className="surface space-y-5 p-6 sm:p-8"><h2 className="text-xl font-extrabold">Preferências</h2><label className="block text-sm font-bold">Seu nome<input className="input mt-2" name="displayName" defaultValue={data.displayName} maxLength={80} required /></label><label className="block text-sm font-bold">Meta diária (minutos)<input className="input mt-2" name="targetMinutes" type="number" min={5} max={240} defaultValue={data.targetMinutes} required /></label><label className="block text-sm font-bold">Fuso horário<input className="input mt-2" name="timezone" defaultValue={data.timezone} required /></label><label className="block text-sm font-bold">Tema<select name="theme" className="input mt-2" defaultValue={data.theme} onChange={(event) => applyTheme(event.target.value)}><option value="system">Sistema</option><option value="light">Claro</option><option value="dark">Escuro</option></select></label><label className="flex items-center gap-3 text-sm font-bold"><input type="checkbox" name="rankingPublic" defaultChecked={data.rankingPublic} />Aparecer no ranking público</label><label className="flex items-center gap-3 text-sm font-bold"><input type="checkbox" name="dailyReminderEnabled" defaultChecked={data.dailyReminderEnabled} />Lembrete diário</label><label className="block text-sm font-bold">Horário do lembrete<input className="input mt-2" name="reminderTime" type="time" defaultValue={data.reminderTime} required /></label>{saved && <p role="status" className="rounded-xl bg-emerald-100 p-3 text-sm text-emerald-900">Configurações salvas.</p>}{error && <p role="alert" className="rounded-xl bg-red-50 p-3 text-sm text-red-800">Confira os dados e tente novamente.</p>}<button type="submit" className="button-primary">Salvar alterações</button></form><div className="space-y-6"><PushPermission enabled={data.pushEnabled} /><section className="surface p-6"><h2 className="text-xl font-extrabold">Privacidade</h2><p className="mt-2 text-sm leading-6 text-muted">Seu progresso é privado. A participação no ranking depende da opção acima. As respostas baixadas são removidas deste dispositivo quando você sai da conta.</p></section></div></div></AppShell>;
}
