import type { ActivityDefinition } from "../index";

export const storyActivities: readonly ActivityDefinition[] = [
  { id: 31, slug: "detetive", title: "Detetive: quem está mentindo?", category: "Aventura", icon: "🕵️", summary: "Leia depoimentos, encontre contradições e apresente a prova.", interests: ["Estudos", "Conversação"], steps: [
    { kind: "choice", context: "Alex: 'I was alone at 8.' Anna: 'I left at 9.' Listen to Bea's testimony.", speechText: "I saw Alex with Anna at eight.", prompt: "Qual frase em inglês contradiz o depoimento de Alex?", options: ["Bea saw Alex with Anna at eight", "Anna left at nine", "Alex spoke at eight", "Nobody saw Alex"], answer: "Bea saw Alex with Anna at eight", explanation: "Alex disse que estava sozinho às 8; Bea diz que o viu acompanhado no mesmo horário." },
    { kind: "write", prompt: "Acuse Alex em inglês e cite a evidência.", modelAnswer: "Alex was not alone at eight because Bea saw him with Anna.", hint: "Use because para ligar acusação e prova." },
  ] },
  { id: 32, slug: "escape-room", title: "Escape room: a última transmissão", category: "Aventura", icon: "⏳", summary: "Interprete instruções de rádio para achar a saída.", interests: ["Estudos", "Viagens", "Programação"], steps: [
    { kind: "scene", context: "Panels: 📦 red box, 📦 blue box, 🖥️ small screen, 🖥️ large screen.", prompt: "Ouça o rádio e escolha em inglês onde procurar a chave.", speechText: "The key isn't inside the red box. Look behind the smallest screen.", options: ["Behind the small screen", "Inside the red box", "Behind the large screen", "Inside the blue box"], answer: "Behind the small screen", explanation: "Behind the smallest screen = atrás da menor tela." },
  ] },
  { id: 33, slug: "alienigena", title: "Um alienígena tentando viver na Terra", category: "Aventura", icon: "👽", summary: "Explique expressões sem interpretá-las ao pé da letra.", interests: ["Conversação", "Estudos"], steps: [
    { kind: "choice", context: "A friend says, 'I'm feeling blue.' The alien reaches for blue paint.", prompt: "Qual explicação em inglês evita a confusão?", options: ["He feels sad, not blue-colored.", "He needs blue paint.", "He wants a blue shirt.", "He is looking at the sky."], answer: "He feels sad, not blue-colored.", explanation: "Feeling blue é uma expressão para sentir tristeza." },
    { kind: "write", prompt: "Responda ao amigo com gentileza em inglês.", modelAnswer: "I'm sorry you're feeling sad. Do you want to talk?", hint: "Use Do you want to talk?" },
  ] },
  { id: 34, slug: "improviso-absurdo", title: "Batalha de improviso absurdo", category: "Aventura", icon: "🎤", summary: "Improviso oral com personagem, situação e palavras obrigatórias.", interests: ["Conversação", "Trabalho"], steps: [
    { kind: "record", context: "You are a pirate at a job interview. Use experience, team and treasure in your answer.", prompt: "Grave em inglês uma resposta curta sobre por que você merece a vaga.", speechText: "Tell me about your experience working with a team.", modelAnswer: "I have experience leading a team. We found treasure together." },
    { kind: "record", context: "Surprise: the interviewer is afraid of boats.", prompt: "Grave em inglês uma segunda resposta adaptando sua história ao medo dele.", speechText: "I'm afraid of boats. Can you still work here?", modelAnswer: "Of course. My teamwork skills also help on land." },
  ] },
  { id: 35, slug: "desarmar-bomba", title: "Desarme a bomba com seu parceiro virtual", category: "Aventura", icon: "💣", summary: "Troque informações com um parceiro virtual e identifique o fio.", interests: ["Conversação", "Estudos", "Programação"], steps: [
    { kind: "choice", context: "Panel: 🔴 red wire next to the blue button; 🟡 yellow wire next to the green light; 🟡 yellow wire next to the blue button. Only your partner has the manual.", prompt: "Qual pergunta em inglês ajuda a receber a instrução necessária?", options: ["Which wire does the manual say to cut?", "What is your favorite film?", "Is it raining outside?", "Can you close the window?"], answer: "Which wire does the manual say to cut?", explanation: "Perguntar pelo fio indicado no manual elimina a informação que falta." },
    { kind: "choice", context: "Your partner says: 'Cut the yellow wire next to the blue button.'", prompt: "Escolha em inglês qual fio você deve cortar.", options: ["The yellow wire next to the blue button", "The yellow wire next to the green light", "The red wire next to the blue button", "All the yellow wires"], answer: "The yellow wire next to the blue button", explanation: "Yellow wire + next to the blue button identifica apenas um fio." },
    { kind: "write", prompt: "Confirme a instrução ao parceiro em inglês antes de agir.", modelAnswer: "Do you mean the yellow wire next to the blue button?", hint: "Use Do you mean...?" },
  ] },
  { id: 36, slug: "mala-misteriosa", title: "A mala de uma pessoa misteriosa", category: "Aventura", icon: "🧳", summary: "Use pistas para construir e defender uma hipótese.", interests: ["Viagens", "Conversação"], steps: [
    { kind: "write", context: "Inside the suitcase: 🎟️ a ticket to a space museum, 👨‍🚀 an astronaut costume, 📝 a note: 'Don't tell my sister.'", prompt: "Quem pode ser o dono da mala? Escreva uma hipótese em inglês.", modelAnswer: "The owner might be going to a costume party near the museum.", hint: "Use might ou could para uma hipótese." },
    { kind: "write", context: "New clue: the ticket is dated tomorrow, not today.", prompt: "Revise sua hipótese em inglês ou defenda a anterior com uma razão.", modelAnswer: "The owner could still be preparing for tomorrow's event.", hint: "Use could, might ou because." },
  ] },
  { id: 37, slug: "restaurante-monstros", title: "Restaurante dos pedidos impossíveis", category: "Aventura", icon: "🍔", summary: "Atenda clientes estranhos respeitando restrições.", interests: ["Viagens", "Conversação"], steps: [
    { kind: "choice", context: "Customer: 'I'd like something red and cold, with no garlic.'\nMenu: cold tomato juice; hot soup; salad with garlic.", prompt: "Leia o pedido em inglês. O que você oferece ao cliente?", options: ["Cold tomato juice", "Hot soup", "Salad with garlic", "Nothing"], answer: "Cold tomato juice", explanation: "Cold tomato juice é vermelho, gelado e não contém alho na descrição." },
    { kind: "write", prompt: "Faça uma pergunta educada em inglês para confirmar uma restrição alimentar.", modelAnswer: "Is there anything else you cannot eat?", hint: "Pergunte se há outros ingredientes proibidos." },
    { kind: "write", context: "The tomato juice is sold out. The menu still has cold beet juice with no garlic.", prompt: "Ofereça uma substituição em inglês e explique por que ela atende ao pedido.", modelAnswer: "We are out of tomato juice, but I can offer cold beet juice. It is red and contains no garlic.", hint: "Use We are out of... but I can offer..." },
  ] },
  { id: 38, slug: "tribunal-desculpas", title: "Tribunal das desculpas esfarrapadas", category: "Aventura", icon: "⚖️", summary: "Defenda um personagem e responda a uma prova surpresa.", interests: ["Negócios", "Conversação"], steps: [
    { kind: "write", context: "Your client is accused of teaching a parrot to reveal passwords. He was away that day.", prompt: "Escreva uma defesa curta em inglês usando because.", modelAnswer: "My client couldn't have taught the parrot because he was away that day.", hint: "Use couldn't have... because..." },
    { kind: "write", context: "Surprise: a recording with your client's voice has arrived.", speechText: "The parrot repeated the client's voice yesterday.", prompt: "Explique em inglês como isso pode ter acontecido sem ignorar a nova evidência.", modelAnswer: "The parrot might have learned the words from an old recording.", hint: "Use might have ou could have." },
  ] },
  { id: 39, slug: "mensagens-futuro", title: "Uma conversa que muda o futuro", category: "Aventura", icon: "📱", summary: "Pergunte, escolha e evite um problema com mensagens incompletas.", interests: ["Conversação", "Estudos"], steps: [
    { kind: "write", context: "Mensagem do futuro: 'Don't let Alex leave before six.'", prompt: "Faça duas perguntas em inglês para esclarecer a mensagem.", modelAnswer: "Who is Alex? Why must he wait until six?", hint: "Pergunte quem é Alex e por que ele deve esperar." },
    { kind: "choice", context: "New message: 'At six, the bridge reopens. Alex needs to cross it safely.'", prompt: "Escolha em inglês a decisão que evita o problema.", options: ["Ask Alex to wait until six", "Tell Alex to leave at five", "Ignore the bridge", "Change the subject"], answer: "Ask Alex to wait until six", explanation: "A ponte só reabre às seis." },
  ] },
  { id: 40, slug: "dublagem", title: "Dublagem de cenas completamente erradas", category: "Aventura", icon: "🎬", summary: "Crie falas para uma cena muda e mude o tom na segunda rodada.", interests: ["Conversação", "Estudos"], steps: [
    { kind: "record", context: "Silent scene: 🐧🐧 argue beside an empty fridge 🧊. One penguin asks, 'Where is the fish?' Apologize without admitting you ate it.", prompt: "Grave a primeira fala em inglês com tom de comédia.", modelAnswer: "I'm sorry the fish disappeared. Maybe it went on vacation!" },
    { kind: "record", context: "The same scene is now a mystery. 'Who opened the fridge last night?'", prompt: "Grave uma nova fala em inglês com pausas e tom misterioso.", modelAnswer: "I'm sorry. The fish is gone... and I don't know who opened the fridge." },
  ] },
];
