import type { ActivityDefinition } from "../index";

export const storyActivities: readonly ActivityDefinition[] = [
  { id: 31, slug: "detetive", title: "Detetive: quem está mentindo?", category: "Aventura", icon: "🕵️", summary: "Leia depoimentos, encontre contradições e apresente a prova.", interests: ["Estudos", "Conversação"], steps: [
    { kind: "choice", context: "Alex: 'I was alone at 8.' Anna: 'I left at 9.' Ouça o depoimento de Bea.", speechText: "I saw Alex with Anna at eight.", prompt: "Qual depoimento contradiz diretamente o de Alex?", options: ["Bea viu Alex com Anna às 8", "Anna saiu às 9", "Alex falou às 8", "Nenhum"], answer: "Bea viu Alex com Anna às 8", explanation: "Alex disse que estava sozinho às 8; Bea diz que o viu acompanhado no mesmo horário." },
    { kind: "write", prompt: "Acuse Alex em inglês e cite a evidência.", modelAnswer: "Alex was not alone at eight because Bea saw him with Anna.", hint: "Use because para ligar acusação e prova." },
  ] },
  { id: 32, slug: "escape-room", title: "Escape room: a última transmissão", category: "Aventura", icon: "⏳", summary: "Interprete instruções de rádio para achar a saída.", interests: ["Estudos", "Viagens", "Programação"], steps: [
    { kind: "scene", context: "Painéis: 📦 caixa vermelha, 📦 caixa azul, 🖥️ tela pequena, 🖥️ tela grande.", prompt: "Ouça o rádio e escolha onde procurar a chave.", speechText: "The key isn't inside the red box. Look behind the smallest screen.", options: ["Atrás da tela pequena", "Dentro da caixa vermelha", "Atrás da tela grande", "Dentro da caixa azul"], answer: "Atrás da tela pequena", explanation: "Behind the smallest screen = atrás da menor tela." },
  ] },
  { id: 33, slug: "alienigena", title: "Um alienígena tentando viver na Terra", category: "Aventura", icon: "👽", summary: "Explique expressões sem interpretá-las ao pé da letra.", interests: ["Conversação", "Estudos"], steps: [
    { kind: "choice", context: "Um amigo diz: 'I'm feeling blue.' O alienígena pega tinta azul.", prompt: "Qual explicação evita a confusão?", options: ["He feels sad, not blue-colored.", "He needs blue paint.", "He wants a blue shirt.", "He is looking at the sky."], answer: "He feels sad, not blue-colored.", explanation: "Feeling blue é uma expressão para sentir tristeza." },
    { kind: "write", prompt: "Responda ao amigo com gentileza em inglês.", modelAnswer: "I'm sorry you're feeling sad. Do you want to talk?", hint: "Use Do you want to talk?" },
  ] },
  { id: 34, slug: "improviso-absurdo", title: "Batalha de improviso absurdo", category: "Aventura", icon: "🎤", summary: "Improviso oral com personagem, situação e palavras obrigatórias.", interests: ["Conversação", "Trabalho"], steps: [
    { kind: "record", context: "Você é um pirata em uma entrevista de emprego. Use experience, team e treasure.", prompt: "Grave uma resposta curta sobre por que você merece a vaga.", speechText: "Tell me about your experience working with a team.", modelAnswer: "I have experience leading a team. We found treasure together." },
    { kind: "record", context: "Surpresa: o entrevistador tem medo de barcos.", prompt: "Grave uma segunda resposta adaptando sua história ao medo dele.", speechText: "I'm afraid of boats. Can you still work here?", modelAnswer: "Of course. My teamwork skills also help on land." },
  ] },
  { id: 35, slug: "desarmar-bomba", title: "Desarme a bomba com seu parceiro virtual", category: "Aventura", icon: "💣", summary: "Troque informações com um parceiro virtual e identifique o fio.", interests: ["Conversação", "Estudos", "Programação"], steps: [
    { kind: "choice", context: "Você vê o painel: 🔴 fio vermelho junto ao botão azul; 🟡 fio amarelo junto à luz verde; 🟡 fio amarelo junto ao botão azul. Só o parceiro virtual vê o manual.", prompt: "Qual pergunta em inglês ajuda a receber a instrução necessária?", options: ["Which wire does the manual say to cut?", "What is your favorite film?", "Is it raining outside?", "Can you close the window?"], answer: "Which wire does the manual say to cut?", explanation: "Perguntar pelo fio indicado no manual elimina a informação que falta." },
    { kind: "choice", context: "O parceiro responde: 'Cut the yellow wire next to the blue button.'", prompt: "Qual fio você deve cortar?", options: ["Amarelo junto ao botão azul", "Amarelo junto à luz verde", "Vermelho junto ao botão azul", "Todos os amarelos"], answer: "Amarelo junto ao botão azul", explanation: "Yellow wire + next to the blue button identifica apenas um fio." },
    { kind: "write", prompt: "Confirme a instrução ao parceiro em inglês antes de agir.", modelAnswer: "Do you mean the yellow wire next to the blue button?", hint: "Use Do you mean...?" },
  ] },
  { id: 36, slug: "mala-misteriosa", title: "A mala de uma pessoa misteriosa", category: "Aventura", icon: "🧳", summary: "Use pistas para construir e defender uma hipótese.", interests: ["Viagens", "Conversação"], steps: [
    { kind: "write", context: "Na mala: 🎟️ ingresso para um museu espacial, 👨‍🚀 fantasia de astronauta, 📝 bilhete: 'Don't tell my sister.'", prompt: "Quem pode ser o dono da mala? Escreva uma hipótese em inglês.", modelAnswer: "The owner might be going to a costume party near the museum.", hint: "Use might ou could para uma hipótese." },
    { kind: "write", context: "Nova pista: o ingresso traz a data de amanhã, não de hoje.", prompt: "Revise sua hipótese ou defenda a anterior com uma razão.", modelAnswer: "The owner could still be preparing for tomorrow's event.", hint: "Use could, might ou because." },
  ] },
  { id: 37, slug: "restaurante-monstros", title: "Restaurante dos pedidos impossíveis", category: "Aventura", icon: "🍔", summary: "Atenda clientes estranhos respeitando restrições.", interests: ["Viagens", "Conversação"], steps: [
    { kind: "choice", context: "Um vampiro pede algo vermelho, gelado e sem alho. Há suco de tomate gelado, sopa quente e salada com alho.", prompt: "O que você oferece?", options: ["Suco de tomate gelado", "Sopa quente", "Salada com alho", "Nada"], answer: "Suco de tomate gelado", explanation: "É vermelho, gelado e não contém alho na descrição." },
    { kind: "write", prompt: "Faça uma pergunta educada em inglês para confirmar uma restrição alimentar.", modelAnswer: "Is there anything else you cannot eat?", hint: "Pergunte se há outros ingredientes proibidos." },
    { kind: "write", context: "O suco de tomate acabou. Há suco de beterraba gelado, sem alho.", prompt: "Ofereça uma substituição ao cliente e explique por que ela atende ao pedido.", modelAnswer: "We are out of tomato juice, but I can offer cold beet juice. It is red and contains no garlic.", hint: "Use We are out of... but I can offer..." },
  ] },
  { id: 38, slug: "tribunal-desculpas", title: "Tribunal das desculpas esfarrapadas", category: "Aventura", icon: "⚖️", summary: "Defenda um personagem e responda a uma prova surpresa.", interests: ["Negócios", "Conversação"], steps: [
    { kind: "write", context: "Seu cliente é acusado de ensinar um papagaio a revelar senhas. Ele estava viajando no dia.", prompt: "Escreva uma defesa curta em inglês usando because.", modelAnswer: "My client couldn't have taught the parrot because he was away that day.", hint: "Use couldn't have... because..." },
    { kind: "write", context: "Surpresa: chegou uma gravação com a voz do cliente.", speechText: "The parrot repeated the client's voice yesterday.", prompt: "Explique como isso pode ter acontecido sem ignorar a nova evidência.", modelAnswer: "The parrot might have learned the words from an old recording.", hint: "Use might have ou could have." },
  ] },
  { id: 39, slug: "mensagens-futuro", title: "Uma conversa que muda o futuro", category: "Aventura", icon: "📱", summary: "Pergunte, escolha e evite um problema com mensagens incompletas.", interests: ["Conversação", "Estudos"], steps: [
    { kind: "write", context: "Mensagem do futuro: 'Don't let Alex leave before six.'", prompt: "Faça duas perguntas em inglês para esclarecer a mensagem.", modelAnswer: "Who is Alex? Why must he wait until six?", hint: "Pergunte quem é Alex e por que ele deve esperar." },
    { kind: "choice", context: "Nova mensagem: 'At six, the bridge reopens. Alex needs to cross it safely.'", prompt: "Qual decisão evita o problema?", options: ["Pedir que Alex espere até as seis", "Mandar Alex sair às cinco", "Ignorar a ponte", "Trocar de assunto"], answer: "Pedir que Alex espere até as seis", explanation: "A ponte só reabre às seis." },
  ] },
  { id: 40, slug: "dublagem", title: "Dublagem de cenas completamente erradas", category: "Aventura", icon: "🎬", summary: "Crie falas para uma cena muda e mude o tom na segunda rodada.", interests: ["Conversação", "Estudos"], steps: [
    { kind: "record", context: "Cena muda: 🐧🐧 discutem diante de uma geladeira vazia 🧊. Missão: peça desculpas sem admitir que comeu o peixe.", prompt: "Grave a primeira fala como comédia.", modelAnswer: "I'm sorry the fish disappeared. Maybe it went on vacation!" },
    { kind: "record", context: "A mesma cena agora é um suspense.", prompt: "Grave uma nova fala com pausas e tom misterioso.", modelAnswer: "I'm sorry. The fish is gone... and I don't know who opened the fridge." },
  ] },
];
