import Link from "next/link";
import { AppShell } from "@/components/AppShell";
import type { DashboardViewProps } from "../Model";
import { SignOutButton } from "@/components/SignOutButton";

export function DashboardView({ data }: DashboardViewProps) {
  const goalPercent = Math.min(100, Math.round(data.todaySeconds / (data.targetMinutes * 60) * 100));
  return <AppShell active="/dashboard"><div className="flex items-start justify-between gap-4"><div><p className="eyebrow">Sua jornada</p><h1 className="mt-2 text-3xl font-extrabold sm:text-4xl">Olá, {data.name} 👋</h1><p className="mt-2 text-muted">Seu próximo passo começa agora.</p></div><SignOutButton userId={data.userId} /></div>
    <section className="mt-8 grid gap-4 sm:grid-cols-2 lg:grid-cols-4" aria-label="Seu progresso"><Stat label="Nível" value={`${data.level}`} detail={`Inglês ${data.cefrLevel}`} /><Stat label="XP total" value={data.totalXp.toLocaleString("pt-BR")} detail="Pontos conquistados" /><Stat label="Sequência" value={`${data.streakDays} dias`} detail="Meta diária atingida" /><Stat label="Palavras estudadas" value={`${data.learnedWords}`} detail={`${data.dueWords} para revisar`} /></section>
    <div className="mt-6 grid gap-6 lg:grid-cols-[1.4fr_1fr]"><section className="surface p-7"><p className="eyebrow">Sua meta diária</p><div className="mt-3 flex items-end justify-between gap-3"><h2 className="text-2xl font-extrabold">Continue avançando</h2><span className="font-extrabold text-primary">{goalPercent}%</span></div><div className="mt-5 h-3 overflow-hidden rounded-full bg-emerald-100" role="progressbar" aria-label="Meta diária" aria-valuenow={goalPercent} aria-valuemin={0} aria-valuemax={100}><div className="h-full rounded-full bg-primary" style={{ width: `${goalPercent}%` }} /></div><p className="mt-3 text-sm text-muted">{Math.floor(data.todaySeconds / 60)} de {data.targetMinutes} minutos de prática validada · {data.todayAnswers} respostas hoje</p><Link href="/study" className="button-primary mt-6">Começar a estudar →</Link></section><section className="surface p-7"><p className="eyebrow">Recomendado para você</p><h2 className="mt-3 text-2xl font-extrabold">{data.dueWords > 0 ? "Revise antes de esquecer" : "Aprenda palavras novas"}</h2><p className="mt-3 leading-7 text-muted">{data.dueWords > 0 ? `${data.dueWords} palavras estão prontas para revisão.` : "Uma sessão curta ajuda a criar constância."}</p><Link href={data.dueWords > 0 ? "/review" : "/study"} className="button-secondary mt-6">{data.dueWords > 0 ? "Revisar agora" : "Estudar agora"}</Link></section></div>
    <section className="mt-6 grid gap-4 sm:grid-cols-3"><Link href="/vocabulary" className="surface p-6 transition hover:border-emerald-400"><span className="text-2xl" aria-hidden>📚</span><h3 className="mt-3 font-extrabold">Vocabulário</h3><p className="mt-1 text-sm text-muted">Explore palavras por nível.</p></Link><Link href="/progress" className="surface p-6 transition hover:border-emerald-400"><span className="text-2xl" aria-hidden>📈</span><h3 className="mt-3 font-extrabold">Seu progresso</h3><p className="mt-1 text-sm text-muted">Veja sua atividade recente.</p></Link><Link href="/review" className="surface p-6 transition hover:border-emerald-400"><span className="text-2xl" aria-hidden>🧠</span><h3 className="mt-3 font-extrabold">Revisão diária</h3><p className="mt-1 text-sm text-muted">Reforce o que já aprendeu.</p></Link></section>
  </AppShell>;
}

function Stat({ label, value, detail }: { label: string; value: string; detail: string }) { return <article className="surface p-5"><p className="text-sm font-bold text-muted">{label}</p><p className="mt-3 text-3xl font-extrabold text-primary">{value}</p><p className="mt-2 text-sm text-muted">{detail}</p></article>; }
